apiVersion: v1
kind: Pod
metadata:
  name: nginx-test
spec:
  volumes:
    - name: share-data
      emptyDir: {}
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: share-data
          mountPath: /share-data
