apiVersion: batch/v1
kind: Job
metadata:
  name: ejemplo-job
spec:
  template:
    spec:
      containers:
      - name: ejemplo-container
        image: ubuntu
        command: ["echo","Hola Mundo"]
      restartPolicy: Never
