apiVersion: v1
kind: Pod
metadata:
  name: nginx-test
  labels:
    app: my-app
    version: v1
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
