apiVersion: v1
kind: Pod
metadata:
  name: nginx-worker-pod
spec:
  nodeSelector:
    role: worker
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
